apiVersion: v1
kind: Pod
metadata:
  name: "rpi-poc-demo-{{ .Values.nodename }}"
spec:
  automountServiceAccountToken: false
  nodeName: {{ .Values.nodename }}
  containers:
  - name: leds
    image: "containers.local:8080/{{ .Values.accountid }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
    volumeMounts:
      - mountPath: /work
        name: led-access
  restartPolicy: OnFailure
  volumes:
  - name: led-access
    hostPath:
      path: /sys/devices/platform/leds/leds
